########################################
# Setting env variables. 
# Change AWSREGION and CONSUL_LICENSE as needed  
# Change values for EKS_CLUSTER_SERVER, EKS_CLUSTER_CLIENT1, EKS_CLUSTER_CLIENT2 if you have different EKS cluster names.
#########################################

export AWSREGION=eu-north-1
export EKS_CLUSTER_SERVER=Consul-cluster-server
export EKS_CLUSTER_CLIENT1=Consul-cluster-client1
export EKS_CLUSTER_CLIENT2=Consul-cluster-client2

export EKS_CLUSTER_SERVER_CTX=$(aws eks --region $AWSREGION update-kubeconfig --name $EKS_CLUSTER_SERVER | grep arn | awk '{print $3}')
export EKS_CLUSTER_CLIENT1_CTX=$(aws eks --region $AWSREGION update-kubeconfig --name $EKS_CLUSTER_CLIENT1 | grep arn | awk '{print $3}')
export EKS_CLUSTER_CLIENT2_CTX=$(aws eks --region $AWSREGION update-kubeconfig --name $EKS_CLUSTER_CLIENT2 | grep arn | awk '{print $3}')

export CONSUL_LICENSE=02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JJYZFU3KNPJHGQTKEKF2FS3KRGFHGSMBSLJVGQ2SMKRATCTSHJF2E23KFGNHHUZZULJWVSMKPK5FGYSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJF4FS2THPFHUITJRJZ4TC22PKRTXUTCUIF4E2MSVORHUORJRJZ4TAMS2K5MTGTTKJEYU6RCRGFHUIY3JJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SFORGVISLUJVCGIVKNNJATMTLKKE3E2VCVOVHEIY3ZJVVES6SOIRTXSV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJPBGFIRLZJRKECM2WIREXOT3KJEYE62SFGFLWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKJF2E2RCFORGUIWSVJVVECNSNNJITMTKUKZQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJEXITKEIV2E2RDEKVGWUQJWJVVFCNSNKRLGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNVHHMYTOJYYWEQ2JONEW2WTTLFLWI6SJNJYDOSLNGF3FUSCWONNFQTLJJ5WHG2K2GJ4HMWLNIZZUYWC2OBRTE3DJMFLXQ4DEJBVXIY3NHEYWIR3MOVNHSML2LEZEM422KNEXGSLNMR3GI3KWPFRG2RTVLEZFK5DDI44XGYKXJY2US3BRHFTFCPJ5FZTXETSDOFUU6SDMJVDDQT2NPJYXCR2UGI2DAMBPGY2WE3ZTMIYSWSKBKR2WURKXJ5DUGWRYGNUU2MLBNRBDIQ2KON2VOZTMGJCGQODQIFLVMOLJGE2WC4DZI5CFCNSCNVCUYNSZIRNDCZCBNNRWCNDEKYYDGMZYKB3W2VTMMF3EUUBUOBFHQSKJHFCDMVKGJRKWCVSQNJVVOSTUMNCDM4DBNQ3G6T3GI5XEWMT2KBFUUUTNI5EFMM3FLJ3XCRTFFNXTO2ZPOMVUCVCONBIFUZ2TF5FVMWLHF5FSW3CHKB3UYN3KIJ4ESN2HJ5QWWNSVMFUWCSDPMVVTAUSUN43TERCRHU6Q


#############################################
#INSTALL CONSUL CLIENT 2 ON THIRD K8S CLUSTER 
#############################################

# Copy tls cert/keys and partition acl tokens. This is needed if tls and acls are enabled.
kubectl get secret consul-consul-ca-cert --context $EKS_CLUSTER_SERVER_CTX -o yaml | kubectl apply --context $EKS_CLUSTER_CLIENT2_CTX -f -
kubectl get secret consul-consul-ca-key --context $EKS_CLUSTER_SERVER_CTX -o yaml | kubectl apply --context $EKS_CLUSTER_CLIENT2_CTX -f -
kubectl get secret consul-consul-partitions-acl-token --context $EKS_CLUSTER_SERVER_CTX -o json | kubectl apply --context $EKS_CLUSTER_CLIENT2_CTX -f -

# Set context, add license, install
# IMPORTANT, make sure you edited your helm-client2.yaml file with the latest COnsul Server's partition service IPs and the current K8AuthHost. 
 
kubectl config use-context $EKS_CLUSTER_CLIENT2_CTX
kubectl create secret generic license --from-literal=key=$CONSUL_LICENSE
helm install consul hashicorp/consul -f helm-client-team2.yaml --wait --debug





